// (c) 2011 Beem Media

//DRAM
MESH_DATA_SECTION( EGMeshBase::egHeader   , H )
MESH_DATA_SECTION( EGMeshBase::egBone     , Bones )
MESH_DATA_SECTION( EGMeshBase::egMtrl     , Mtrls )
MESH_DATA_SECTION( EGMeshBase::egSubMesh  , SubMeshes )
MESH_DATA_SECTION( EGMeshBase::egTextNode , TextNodes )
MESH_DATA_SECTION( eg_char                , Strings )

//VRAM:
MESH_DATA_SECTION( egv_vert_mesh          , Vertexes )
MESH_DATA_SECTION( egv_index              , Indexes )