// (c) 2011 Beem Media

#pragma once

#include "EGRendererTypes.h"

class EGSkelBase 
{
public:

	static const eg_uint SKEL_ID      = 0x4C4B534C; //"LSKL"
	static const eg_uint SKEL_VERSION = 106;

	static const eg_uint MAX_BONES    = RENDERER_MAX_BONES+1; //Probably should take this from Renderer.h

	struct egHeader
	{
		//Header Info:
		eg_uint nID = 0;
		eg_uint nVersion = 0;

		//Data counts:
		#define SKEL_DATA_SECTION( _type_ , _var_ ) eg_uint n##_var_##Count = 0;
		#include "EGSkelDataSections.inc"
		#undef SKEL_DATA_SECTION

		//Data offsets (from start of m_pMem):
			#define SKEL_DATA_SECTION( _type_ , _var_ ) eg_uint Ofs##_var_ = 0;
			#include "EGSkelDataSections.inc"
			#undef SKEL_DATA_SECTION
	};

	struct egJoint
	{
		eg_uint      nStrOfsName = 0;
		eg_uint      nParent = 0;
		eg_transform Trans = CT_Default;
		//The following info is not currently
		//stored in the eskel format, and is generated by CalcExData
		eg_transform matLocal = CT_Default;
		eg_transform matFinal = CT_Default;
		eg_transform matFinalInv = CT_Default;
		eg_uint      nJointRef = 0;
	};

	struct egAnim
	{
		enum LOOP_M:eg_uint
		{
			LOOP_ONCE,
			LOOP_LOOPING,
			LOOP_LOOP_BACK,
		};

		eg_string_crc NameCrc = CT_Clear;
		eg_uint       nStrOfsName = 0;          //Animation name.
		eg_uint       nFirstFrame = 0;   //First frame of anim.
		eg_uint       nNumFrames = 0;    //Number of frams in the anim.
		eg_uint       nLoopingFrames = 0; //Number of frames to loop (unused, may get dropped).
		eg_uint       nNext = 0;          //If the type is MODE_ONCE, nNext points to the next animation to play.
		eg_real       fRate = 0.f;         //Recommended rate of animation.
		LOOP_M        LoopMode = LOOP_M::LOOP_ONCE;        //How the end of the animation is treated.
	};

public:

	EGSkelBase();
	~EGSkelBase();

	eg_bool IsLoaded()const;

	eg_uint GetNumFrames()const;
	eg_uint GetNumJoints()const;
	eg_uint GetNumKeyFrames()const;
	eg_uint GetNumAnims()const;
	eg_uint GetParentBoneRef(eg_uint nBone)const;
	eg_cpstr GetBoneName(eg_uint nBone)const;	
	const eg_transform* GetBaseTransform(eg_uint nJoint)const;
	eg_uint GetFrameFromTime(eg_string_crc AnimationId, eg_real fTime, eg_real* pFrameTime, eg_uint* pFrame2)const;
	eg_uint GetFrameFromTime_Looping(eg_string_crc AnimationId, eg_real fTime, eg_real* pFrameTime, eg_uint* pFrame2)const;
	eg_uint GetFrameFromTime_Once(eg_string_crc AnimationId, eg_real fTime, eg_real* pFrameTime, eg_uint* pFrame2)const;
	eg_uint GetFrameFromTime_LoopBack(eg_string_crc AnimationId, eg_real fTime, eg_real* pFrameTime, eg_uint* pFrame2)const;
	const egAnim* GetAnimByCrc( eg_string_crc Crc )const;

	void ComputeFrameBones( eg_uint nFrame1 , eg_uint nFrame2 , eg_real t , eg_transform* aTransBonesTarget );
	void ComputeFrameBones( eg_uint nFrame1_1 , eg_uint nFrame2_1 , eg_real t1 , EGSkelBase* pSkel2 , eg_uint nFrame_2 , eg_real t2 , eg_transform* aTransBonesTarget );

protected:

	//////////////////////////
	//BINARY FILE FORMAT START
	#define SKEL_DATA_SECTION( _type_ , _var_ ) _type_* m_p##_var_ = nullptr;
	#include "EGSkelDataSections.inc"
	#undef SKEL_DATA_SECTION
	//BINARY FILE FORMAT END
	////////////////////////

	//Additional information that is stored:
	egHeader        m_H = egHeader();
	eg_size_t       m_nMemSize = 0; //Size of the file in binary form (see chunk below).
	eg_byte*        m_pMem = nullptr;          //The memory allocation chunk.

protected:

	//Helper functions:
	eg_transform* GetLocalTransform(eg_uint nBone, eg_uint nFrame);
	void EG_INLINE ComputeFrameBones_Algorithm( const eg_transform*const aL , eg_transform* aTransBonesTarget );
	void SetPointers(const egHeader& Header);	
};
