// (c) Beem Media - Generated Code Definition for "EGGcxBuildData.h"

#if defined( EGRFL_INCLUDE_SOURCE_HEADER )
#include "EGGcxBuildData.h"
#include "EGGcxBuildData.reflection.h"
#endif // defined( EGRFL_INCLUDE_SOURCE_HEADER )

EGRFL_IMPL_STRUCT_BEGIN( gcxBuildTileData )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildTileData , eg_d_string , TerrainType )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildTileData , eg_real , TopOffset )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildTileData , eg_real , BottomOffset )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildTileData , eg_real , NavGraphOffset )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildTileData , eg_string_crc , GroundMaterial )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildTileData , eg_string_crc , CeilingMaterial )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildTileData , eg_real , CeilingThickness )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildTileData , eg_real , CeilingHeight )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildTileData , eg_bool , bCanWalkOn )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildTileData , eg_bool , bHasGround )
EGRFL_IMPL_STRUCT_END( gcxBuildTileData )

EGRFL_IMPL_STRUCT_BEGIN( gcxDoorData )
	EGRFL_IMPL_STRUCT_ITEM( gcxDoorData , eg_real , Height )
	EGRFL_IMPL_STRUCT_ITEM( gcxDoorData , eg_real , Width )
	EGRFL_IMPL_STRUCT_ITEM( gcxDoorData , eg_real , TorchDistanceFromGround )
	EGRFL_IMPL_STRUCT_ITEM( gcxDoorData , eg_asset_path , EntityDefinition )
EGRFL_IMPL_STRUCT_END( gcxDoorData )

EGRFL_IMPL_STRUCT_BEGIN( gcxBuildWallData )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildWallData , eg_int , PaletteIndex )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildWallData , eg_string_crc , WallMaterial )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildWallData , eg_string_crc , PillarMaterial )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildWallData , eg_real , Height )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildWallData , eg_real , WallThickness )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildWallData , eg_real , PillarThickness )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildWallData , eg_color32 , MapWallColor )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildWallData , gcxDoorData , StandardDoorData )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildWallData , gcxDoorData , SecretDoorData )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildWallData , eg_real , TorchRange )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildWallData , eg_color32 , TorchColor )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildWallData , eg_real , TorchDistanceFromWall )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildWallData , eg_real , TorchDistanceFromGround )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildWallData , eg_asset_path , TorchEntityDefinition )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildWallData , eg_bool , bDoorsHaveTorches )
EGRFL_IMPL_STRUCT_END( gcxBuildWallData )

EGRFL_IMPL_STRUCT_BEGIN( gcxBuildMaterialData )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildMaterialData , eg_string_crc , MaterialId )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildMaterialData , eg_asset_path , Texture0Path )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildMaterialData , eg_asset_path , Texture1Path )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildMaterialData , eg_asset_path , Texture2Path )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildMaterialData , eg_asset_path , Texture3Path )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildMaterialData , eg_asset_path , ShaderPath )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildMaterialData , eg_vec2 , TextureUVScale )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildMaterialData , eg_color32 , AutomapGroundColor1 )
	EGRFL_IMPL_STRUCT_ITEM( gcxBuildMaterialData , eg_color32 , AutomapGroundColor2 )
EGRFL_IMPL_STRUCT_END( gcxBuildMaterialData )

EGRFL_IMPL_CHILD_STRUCT_BEGIN( EGGcxBuildData , EGDataAsset )
	EGRFL_IMPL_STRUCT_ITEM( EGGcxBuildData , eg_real , m_WallLength )
	EGRFL_IMPL_STRUCT_ITEM( EGGcxBuildData , eg_vec2 , m_RegionHeightDims )
	EGRFL_IMPL_STRUCT_ITEM( EGGcxBuildData , eg_bool , m_bAllTilesHaveCeilings )
	EGRFL_IMPL_STRUCT_ITEM( EGGcxBuildData , eg_bool , m_bAnyTileWithMarkerIsSafe )
	EGRFL_IMPL_STRUCT_ITEM( EGGcxBuildData , eg_bool , m_bTilesWithMonstersAreSafe )
	EGRFL_IMPL_STRUCT_ITEM_ARRAY( EGGcxBuildData , gcxBuildTileData , m_TileInfos )
	EGRFL_IMPL_STRUCT_ITEM_ARRAY( EGGcxBuildData , gcxBuildWallData , m_WallInfos )
	EGRFL_IMPL_STRUCT_ITEM_ARRAY( EGGcxBuildData , gcxBuildMaterialData , m_MaterialInfos )
EGRFL_IMPL_CHILD_STRUCT_END( EGGcxBuildData , EGDataAsset )

