// (c) 2019 Beem Media. All Rights Reserved.

#include "EGMake_PrepPlatform.h"
#include "EGToolsHelper.h"
#include "EGPath2.h"
#include "EGOsFile.h"
#include "EGEdUtility.h"
#include "EGMakeBuildConfig.h"
#include "EGFileData.h"
#include "EGLibFile.h"
#include "EGPath2.h"
#include "EGFileData.h"
#include "EGTargetPlatform.h"
#include "EGEdUtility.h"

static void EGMakePrepPlatform_GenerateTargetPlatformCode( const eg_d_string8& TargetPlatformName )
{
	const eg_d_string16 GeneratedCodeDirectory = EGPath2_CleanPath( *EGSFormat16( L"{0}/generated_code/platform/" , EGToolsHelper_GetEnvVar( "EGOUT" ).String() ) , '/' );
	EGOsFile_CreateDirectory( *GeneratedCodeDirectory );

	EGFileData GeneratedPlatformCode( eg_file_data_init_t::HasOwnMemory );

	GeneratedPlatformCode.WriteStr8( *EGSFormat8( "// GENERATED BY {0} DO NOT MODIFY\r\n" , __FUNCTION__ ) );

	const eg_target_platform_t TargetPlatform = EGTargetPlatform_GetPlatformFromName( *TargetPlatformName );

	GeneratedPlatformCode.WriteStr8( "\r\n" );

	for( eg_size_t PlatformIndex=0; PlatformIndex<EGTargetPlatform_GetNumPlatforms(); PlatformIndex++ )
	{
		const eg_target_platform_t PlatformType = static_cast<eg_target_platform_t>(PlatformIndex);
		eg_cpstr PlatformName = EGTargetPlatform_GetPlatformNameByIndex( PlatformIndex );
		const eg_bool bIsThisPlatform = TargetPlatform == PlatformType;

		if( bIsThisPlatform )
		{
			GeneratedPlatformCode.WriteStr8( *EGSFormat8( "#define __PLATFORM_{0}__\r\n" , PlatformName ) );
			GeneratedPlatformCode.WriteStr8( *EGSFormat8( "#define __PLATFORM_NAME__ \"{0}\"\r\n" , PlatformName ) );
		}
	}

	GeneratedPlatformCode.WriteStr8( "\r\n" );

	for( eg_size_t PlatformIndex=0; PlatformIndex<EGTargetPlatform_GetNumPlatforms(); PlatformIndex++ )
	{
		const eg_target_platform_t PlatformType = static_cast<eg_target_platform_t>(PlatformIndex);
		eg_cpstr PlatformName = EGTargetPlatform_GetPlatformNameByIndex( PlatformIndex );
		const eg_bool bIsThisPlatform = TargetPlatform == PlatformType;

		GeneratedPlatformCode.WriteStr8( *EGSFormat8( "#define IS_PLATFORM_{0} ({1})\r\n" , PlatformName , bIsThisPlatform ? 1 : 0 ) );
	}

	const eg_d_string16 GeneratedFilename = GeneratedCodeDirectory + L"EGTargetBuildPlatform.generated.hpp";
	EGEdUtility_SaveIfUnchanged( *GeneratedFilename , GeneratedPlatformCode , false );
}

int EGMakePrepPlatform_main( int argc , char* argv[] )
{
	unused( argc , argv );

	const eg_bool bInCorrectDir = EGToolsHelper_SetDirToSolutionDir();

	if( !bInCorrectDir )
	{
		EGLogf( eg_log_t::General , "Couldn't find the solution file." );
		return -1;
	}
	
	EGEdUtility_Init();

	EGLogf( eg_log_t::General , "Preparing platform..." );

	eg_d_string8 TargetPlatformName;

	eg_bool bNextIsPlatform = false;
	for (int i = 0; i < argc; i++)
	{
		if (bNextIsPlatform)
		{
			bNextIsPlatform = false;
			TargetPlatformName = argv[i];
		}

		if (EGString_EqualsI(argv[i], "-platform"))
		{
			bNextIsPlatform = true;
		}
	}

	if (TargetPlatformName.Len() == 0)
	{
		TargetPlatformName = EGTargetPlatform_GetPlatformNameByIndex(0);
	}

	EGLogf( eg_log_t::General , "Platform: %s" , *TargetPlatformName );

	const eg_d_string16 BinDir = EGPath2_CleanPath( *EGSFormat16( L"{0}/bin" , EGToolsHelper_GetEnvVar( "EGOUT" ).String() ) , '/' );
	const eg_d_string8 GameId = *EGToolsHelper_GetBuildVar( "EGGAME" );

	if( !EGOsFile_DoesDirExist( *BinDir ) )
	{
		EGOsFile_CreateDirectory( *BinDir );
	}

	EGMakePrepPlatform_GenerateTargetPlatformCode( TargetPlatformName );

	EGEdUtility_Deinit();
	return 0;
}
